backend:
  name: git-gateway
  branch: main  # use "main" ou "master", conforme seu branch no GitHub

media_folder: "assets/uploads"      # onde as imagens vão ser salvas no repositório
public_folder: "/assets/uploads"    # caminho público das imagens no site

collections:
  - name: "produtos"
    label: "Produtos"
    folder: "content/produtos"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Nome", widget: "string" }
      - { name: "price", label: "Preço", widget: "number" }
      - { name: "image", label: "Imagem", widget: "image" }
      - { name: "category", label: "Categoria", widget: "string" }
