backend:
  name: git-gateway
  branch: main # branch principal

media_folder: "images/uploads" # onde ficam as fotos
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Produtos"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nome", name: "title", widget: "string" }
      - { label: "Descrição", name: "description", widget: "text" }
      - { label: "Preço", name: "price", widget: "number" }
      - { label: "Imagem", name: "image", widget: "image" }
